export const amenitiesOptions = [
  'Accepts Credit Cards',
  'Parking',
  'Wi-Fi',
  'Wheelchair Accessible',
  'Outdoor Seating',
  'Delivery',
  'Curbside Pickup',
  'Lounge Area',
  'Pet Friendly',
  'Cash Accepted',
  'ATM On-Site',
  'Private Consultation',
  'Educational Materials',
];